name 'graphite-cluster'
maintainer 'Olivier Bazoud'
maintainer_email 'olivier.bazoud@gmail.com'
license 'Apache 2.0'
description 'Installs/Configures graphite-cluster'
long_description 'Installs/Configures graphite-cluster'
version '0.1.0'
